### ISSUE TITLE
Performance of hashing

### ISSUE THREAD

**Issue by sostock** [sostock/HalfIntegers.jl#3]
FWIW, there does seem to be a small benefit to the custom `hash` function:
```
julia> using WignerSymbols, HalfIntegers, BenchmarkTools

julia> x = rand(-1000:1000, 10000);

julia> xfloat = x/2;

julia> xrat = x.//2;

julia> xhalf = half.(x);

julia> xwig = WignerSymbols.HalfInteger.(x, 2);

julia> y = hash.(x);

julia> @benchmark map!(hash, $y, $x)
BenchmarkTools.Trial: 
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     26.254 μs (0.00% GC)
  median time:      27.258 μs (0.00% GC)
  mean time:        28.118 μs (0.00% GC)
  maximum time:     142.009 μs (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     1

julia> @benchmark map!(hash, $y, $xfloat)
BenchmarkTools.Trial: 
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     36.866 μs (0.00% GC)
  median time:      38.995 μs (0.00% GC)
  mean time:        39.603 μs (0.00% GC)
  maximum time:     132.436 μs (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     1

julia> @benchmark map!(hash, $y, $xrat)
BenchmarkTools.Trial: 
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     96.417 μs (0.00% GC)
  median time:      103.466 μs (0.00% GC)
  mean time:        106.371 μs (0.00% GC)
  maximum time:     300.126 μs (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     1

julia> @benchmark map!(hash, $y, $xhalf)
BenchmarkTools.Trial: 
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     175.342 μs (0.00% GC)
  median time:      177.345 μs (0.00% GC)
  mean time:        184.564 μs (0.00% GC)
  maximum time:     602.389 μs (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     1

julia> @benchmark map!(hash, $y, $xwig)
BenchmarkTools.Trial: 
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     93.089 μs (0.00% GC)
  median time:      94.630 μs (0.00% GC)
  mean time:        98.162 μs (0.00% GC)
  maximum time:     249.477 μs (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     1
```
So the custom `hash` performs as the one for rational, which however is still much slower than the one for `Float64`. The far better solution thus seems to be to just convert to `Float64`:
```
julia> @benchmark map!(z->hash(float(z)), $y, $xhalf)
BenchmarkTools.Trial: 
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     43.134 μs (0.00% GC)
  median time:      44.856 μs (0.00% GC)
  mean time:        46.925 μs (0.00% GC)
  maximum time:     163.442 μs (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     1
```

_Originally posted by @Jutho in https://github.com/sostock/HalfIntegers.jl/issues/2#issuecomment-483844092_

**Comment by sostock** [comment]
Thanks for the comment, @Jutho, I was not aware of the performance differences. In fact, I didn’t even notice that most common integer and floating-point types have [specialized `Base.hash` methods](https://github.com/JuliaLang/julia/blob/5d12d8696caf1d1ef1a86da9dab2cc2d43d3da09/base/float.jl#L564-L569) and do not even use `Base.decompose`.

In this case, I think it would be nice to have a specialized `Base.hash` implementation based on [that from WignerSymbols.jl](https://github.com/Jutho/WignerSymbols.jl/blob/6ddbd340b0d61e0bdbaabd17b92ffd9985ef180f/src/halfinteger.jl#L107-L119).

Regarding the proposal to just convert to a floating-point type, we would have to discuss whether we want `HalfIntegers` with the same `Float64` approximation to yield the same hashes. This is not the case for `Integer`s and `Rational`s:
```julia
julia> hash(typemax(Int)) == hash(typemax(Int)-1)
false

julia> hash(float(typemax(Int))) == hash(float(typemax(Int)-1))
true

julia> hash(typemax(Int)//2) == hash(typemax(Int)//2-1)
false

julia> hash(float(typemax(Int)//2)) == hash(float(typemax(Int)//2-1))
true

julia> hash(typemax(HalfInt)) == hash(typemax(HalfInt)-1)
false

julia> hash(float(typemax(HalfInt))) == hash(float(typemax(HalfInt)-1))
true
```
I would prefer to keep the current behavior, which mirrors that of `Rational`, regardless of the substantial performance benefits of converting to `Float64`, but I am open to discussion.

**Comment by Jutho** [comment]
As far as I remember, the custom `hash` in WignerSymbols.jl is just that of `Rational`, where I hardcoded the denominator to be `2`. Maybe by studying the `hash` function of `Float64` and `Int64`, we can see how to make the custom `hash` function more efficient.

**Comment by sostock** [comment]
In ab4d7db, I have implemented a custom `hash` method similar to the one in WignerSymbols.jl:
https://github.com/sostock/HalfIntegers.jl/blob/ab4d7dba5bdb6c23d999642e0279f81fc0729a87/src/HalfIntegers.jl#L155-L172
Note that the custom implementation is only used for integer types with ≤ 64 bits. For `Int128`, `UInt128` and `BigInt`, the fallback using `Base.decompose` is used. This matches the implementation for `Rational`s and my benchmarks show that this is indeed more performant (at least for `BigInt`, for `Int128` and `UInt128` the performance is about the same).

**Comment by Jutho** [comment]
Great. I guess you are preparing a release now? I will then update WignerSymbols.jl accordingly.

**Comment by sostock** [comment]
Yes, I am currently registering the package: https://github.com/JuliaRegistries/General/pull/1249
