### ISSUE TITLE
Multiplication and division

### ISSUE THREAD

**Issue by sostock** [sostock/HalfIntegers.jl#4]
> I don’t think it would be wise to make standard arithmetic operations error on `HalfInteger`s. After all, you probably _do_ want to use them in calculations, and division of two `Int`s does also not throw an error.

That's a good point, I forgot that there is a precedent for this with integer division. With that in mind, I think it's fine if the division of `Half`s is consistent with that and also results in a float.

But it still feels weird that multiplication would leave the space. And it does that only occasionally (i.e. not if one factor is an integer). So it means that you really have to mentally keep track of types in your expressions.

Rational would be slightly better since you would not lose precision at least, so it might be a good compromise. I still think an argument can be made that if you do arithmetic with half-integers, you don't want to end up with floating point numbers accidentally.

_Originally posted by @mortenpi in https://github.com/sostock/HalfIntegers.jl/issues/2#issuecomment-483964590_

**Comment by sostock** [comment]
Whether one prefers floats or `Rational`s probably depends on the specific use case. I decided in favor of floats because, when I multiply two half-integers, I am rarely concerned about the loss of precision but usually about the loss of performance – after all, I am doing numerical calculations, not number theory. For example, in `sqrt((2J₁+1)*(2J₂+1))`, I would not gain anything by using `Rational`s – and this is a typical use case, since I use `HalfInteger`s mostly for angular momentum quantum numbers.

Of course, one could argue that this package shouldn’t just appeal to atomic physicists but also to people who want to do exact calculations. But in this case (i.e., if you want to do exact calculations, and use multiplication of `HalfInteger`s a lot), why not use `Rational`s instead of `HalfInteger`s from the start? I would argue that using `HalfIntegers` instead of `Rational`s for such cases does not have a lot of benefits, and just makes it easier to introduce type-instabilities by accident.

But I am open to discuss this further – after all, my first implementation actually used `Rational`s for the products of `HalfInteger`s.

Another proposal that could satisfy users who prefer `Rational`s (or errors, as initially suggested) would be to document a simple interface for defining own `HalfInteger` types. These types would then follow the behavior of the `Half{T}` type except for those methods which the user overwrites – in this case, probably `Base.:*`, `Base.:/` and `Base.promote_rule`. One could even use this specific case (a `HalfInteger` type that results in `Rational`s when multiplied) as an example in the documentation of the interface.

**Comment by mortenpi** [comment]
I am also working with angular momenta. But once I have decided that I need to represent the half-integers exactly, I am usually doing some discrete math, such as figuring out the number or states etc. `(2J₁+1)*(2J₂+1)` is a good example of when you're ending up with an unwanted float, even though the number of states should always be an integer.

But it's hard to solve that in general if you still want to have the operations defined. `Rational`s would not really help _that_ much either (the value will be exact, but still have a weird type, e.g. you can't generate a range for array indices without converting first).

On the other hand, you make a good point that you need to keep the numerical parts in mind as well, such as `sqrt((2J₁+1)*(2J₂+1))`. So I think I agree with you here now that just consistently (and following the precedent with `Int`s in Base) ending up with floats is the simplest and most useful approach here. If the behaviour is clearly documented then it should not be a problem for the user to know that they have to add in the necessary type conversions in the right places when they are doing discrete stuff.

And if someone needs a "safer" half-integer type, then, as you say, adding a custom type is the way to go. Maybe we'll have a `SafeHalfInteger` or something in the package at some point.

**Comment by sostock** [comment]
Indeed, `(2J₁+1)*(2J₂+1)` is an example in which one could (and would want to) work with integers, and only due to the `sqrt` it should become a floating-point number. In this regard, the example I chose was not the best one.

In this specific case, one can use `twice(J₁)` instead of `2J₁` to get an integer.

However, `(twice(J₁)+1)*(twice(J₂)+1)` is much harder to read than `(2J₁+1)*(2J₂+1)`. Maybe it would be worthwile to write a macro that replaces the integer literal `2` when used in a multiplication? Something like
```julia
@use_integers_when_possible (2J₁+1)*(2J₂+1)
```
would expand to
```julia
(twice(J₁)+1)*(twice(J₂)+1)
```
 (of course, one should think of a shorter name than `@use_integers_when_possible`)

**Comment by sostock** [comment]
I have now documented the behavior regarding multiplication and division (https://sostock.github.io/HalfIntegers.jl/dev/manual/#Arithmetic-operations-1), but have not yet written anything about how to implement custom `HalfInteger` types.

**Comment by sostock** [comment]
@mortenpi I have now documented how to implement a custom `HalfInteger` type (https://sostock.github.io/HalfIntegers.jl/dev/manual/#Custom-HalfInteger-types-1). If you think this is sufficient then I think we can close this issue.

**Comment by mortenpi** [comment]
Yes! I read through the section and it looks great, very nicely explained! Also, I think the default behavior you have is actually the better one now, so yes, I agree that there is nothing left to do here :slightly_smiling_face: 

Relatedly, I don't think there are any blockers for registering the package?

**Comment by sostock** [comment]
Yes, I think there is nothing that blocks registration. I will probably register the package tomorrow.
