### ISSUE TITLE
Extension of gcd and lcm to HalfIntegers

### ISSUE THREAD

**Issue by sostock** [sostock/HalfIntegers.jl#5]
> After all, gcd and lcm are well-defined for rational numbers

Hmm..  it is not entirely clear what the definition is actually. LCM and GCD both reduce down to divisibility, and for me, the way to generalize is, [following Wikipedia, via integral domains](https://en.wikipedia.org/wiki/Divisor#Definition).

Based on that, currently from the code `lcm(3/2, 2) = 6`, but AFAICT it should be `3`, since `3/2 | 3` (`3/2 * 2 = 3`) and `2 | 3` (`2 * 3/2 = 3`).

As for rationals, all rational numbers are common multiples of any pair of rational numbers, since every rational (other than 0) divides every other rational? There is a related issue: JuliaLang/julia#27039

_Originally posted by @mortenpi in https://github.com/sostock/HalfIntegers.jl/issues/2#issuecomment-483964590_

**Comment by sostock** [comment]
Okay, so it seems that lcm and gcd are not as “well-defined” as I had hoped – there are at least two definitions. I was not aware of JuliaLang/julia#27039, thanks for bringing this to my attention.

The definition that I chose is the one that leads to the correct behavior of [`Base.intersect(::StepRange, ::StepRange)`](https://github.com/JuliaLang/julia/blob/95a52a5d6210ce07b54f1c8cb74eea88f0cd9eee/base/range.jl#L775-L818) – which leads me to the conclusion that it would be the most useful one to apply in Julia. 

But since people have different opinions on which definition to use, and `lcm(::HalfInteger...)` and `gcd(::HalfInteger...)` are not needed anymore in the current implementation, I would agree that it’s best to delete them for now. When JuliaLang/julia#27039 has reached a conclusion on whether to implement `lcm` and `gcd` for rationals, we can add them again.

**Comment by sostock** [comment]
By the way, @mortenpi, I don’t see how lcm(3/2, 2) = 3 conforms to any definition of divisibility that I am aware of. If one chooses to define
> *m* | *n*  ⇔  there exists an element *k* **of the integral domain** such that *mk* = *n*,

then one has to choose an integral domain first. The half-integers do not form an integral domain (as they are not closed under multiplication). By using the rational numbers as integral domain, one gets lcm(3/2, 2) = 1.

On the other hand, if one defines
> *m* | *n*  ⇔  there exists an **integer** *k* such that *mk* = *n*,

one gets lcm(3/2, 2) = 6. This is the definition that I used in the code.

**Comment by sostock** [comment]
Methods for `Base.lcm`, `Base.gcd` and `Base.gcdx` were removed in 3b3a3f1b4409bb0e3dc54a0a33c3608e1fbfaeca

**Comment by mortenpi** [comment]
Yeah, that's true that half-integers are not an integral domain. But the definition of divisibility should still be consistent when you try to find `k` in the set of all half-integers, i.e.:

> m | n ⇔ there exists an element k such that mk = n

In which case `lcm(3/2, 2) = 3` I believe.

I also actually agree that trying to find `k` from the set of integers would be an equally intuitive way to define divisibility. But there does not seem to be a correct way™ to generalize, which is why it feels like it might make sense to leave `Base.gcd` and `Base.lcm` just for integers.
