### ISSUE TITLE
Relation to FixedPointNumbers.jl

### ISSUE THREAD

**Issue by goretkin** [sostock/HalfIntegers.jl#8]
I just noticed this package on JuliaHub, and it occurred to me that it appears be related to 
https://github.com/JuliaMath/FixedPointNumbers.jl

```
julia> a = Fixed{Int32, 1}(1.5)
1.5Q30f1

julia> a.i
3
```

Might be worth pointing out a connection in the README

**Comment by sostock** [comment]
Sounds good, I added a paragraph to the end of the README. Let me know if you would add or change something.
